global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'myexample'
    metrics_path: '/actuator/prometheus'
    static_configs:
            - targets: ['34.125.195.9:8080'] ## only for demo purposes don't use host.docker.internal in production
